name: CI

on:
  push:
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    # 모든 실행 단계를 meetifyr 폴더 안에서 수행하도록 설정
    defaults:
      run:
        working-directory: ./meetifyr

    steps:
      - name: Check out the codes
        uses: actions/checkout@v4

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v4
        with:
          key: poetry-1.8.5
          path: ~/.local/

      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.5

      - name: Register Poetry bin
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        id: cache-venv
        uses: actions/cache@v4
        with:
          # working-directory 설정 덕분에 ./meetifyr/poetry.lock 파일을 자동으로 찾습니다.
          key: python-${{ steps.setup-python.outputs.python-version }}-poetry-lock-${{ hashFiles('meetifyr/poetry.lock') }}-toml-${{ hashFiles('meetifyr/pyproject.toml') }}-poetry-1.8.5
          path: /home/runner/.cache/pypoetry/virtualenvs/

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Run Black
        run: poetry run black . --check

      - name: Run ruff
        run: |
          poetry run ruff check --select I
          poetry run ruff check

      - name: Run Mypy
        run: poetry run mypy .

  test:
    needs: static-analysis
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./meetifyr

    steps:
      - name: Check out the codes
        uses: actions/checkout@v4

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v4
        with:
          key: poetry-1.8.5
          path: ~/.local/

      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.5

      - name: Register Poetry bin
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        id: cache-venv
        uses: actions/cache@v4
        with:
          key: python-${{ steps.setup-python.outputs.python-version }}-poetry-lock-${{ hashFiles('meetifyr/poetry.lock') }}-toml-${{ hashFiles('meetifyr/pyproject.toml') }}-poetry-1.8.5
          path: /home/runner/.cache/pypoetry/virtualenvs/

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Run tests
        run: |
          poetry run coverage run -m pytest .
          poetry run coverage report -m